services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9443:9443" # HTTPS Web GUI (Required)
      #- "8000:8000" # Edge Agent port (Optional, only needed if connecting remote Docker nodes)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only Docker socket access
      - ./portainer_data:/data # Persistent storage for settings and users

volumes:
  portainer_data: