services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    ports:
      - '10.10.10.10:4040:4040'
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    command: 
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"