services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr2
    ports:
      - "5156:5055"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./seerr/config:/app/config
    restart: unless-stopped
