services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr2
    ports:
      - "7979:7878"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
    restart: unless-stopped

